/* tslint:disable */
/* eslint-disable */
/**
 * Swagger Petstore - OpenAPI 3.0 - version 1.0.27
 *
 * This is a sample Pet Store Server based on the OpenAPI 3.0 specification.  You can find out more about
 Swagger at [https://swagger.io](https://swagger.io). In the third iteration of the pet store, we&#x27;ve switched to the design first approach!
 You can now help us improve the API whether it&#x27;s by making changes to the definition itself or to the code.
 That way, with time, we can improve the API in general, and expose some of the new features in OAS3.

 Some useful links:
 - [The Pet Store repository](https://github.com/swagger-api/swagger-petstore)
 - [The source API definition for the Pet Store](https://github.com/swagger-api/swagger-petstore/blob/master/src/main/resources/openapi.yaml)
 *
 * OpenAPI version: 3.0.4
 *
 * Contact:
 *
 * NOTE: This file is auto generated by the alova's vscode plugin.
 *
 * https://alova.js.org/devtools/vscode
 *
 * **Do not edit the file manually.**
 */
import type { Alova, AlovaMethodCreateConfig, AlovaGenerics, Method } from 'alova';
import type { $$userConfigMap, alovaInstance } from './index';
import type apiDefinitions from './apiDefinitions';

type CollapsedAlova = typeof alovaInstance;
type UserMethodConfigMap = typeof $$userConfigMap;

type Alova2MethodConfig<Responded> =
  CollapsedAlova extends Alova<
      AlovaGenerics<
        any,
        any,
        infer RequestConfig,
        infer Response,
        infer ResponseHeader,
        infer L1Cache,
        infer L2Cache,
        infer SE
      >
    >
    ? Omit<
      AlovaMethodCreateConfig<
        AlovaGenerics<Responded, any, RequestConfig, Response, ResponseHeader, L1Cache, L2Cache, SE>,
        any,
        Responded
      >,
      'params'
    >
    : never;

// Extract the return type of transform function that define in $$userConfigMap, if it not exists, use the default type.
type ExtractUserDefinedTransformed<
  DefinitionKey extends keyof typeof apiDefinitions,
  Default
> = DefinitionKey extends keyof UserMethodConfigMap
  ? UserMethodConfigMap[DefinitionKey]['transform'] extends (...args: any[]) => any
    ? Awaited<ReturnType<UserMethodConfigMap[DefinitionKey]['transform']>>
    : Default
  : Default;
type Alova2Method<
  Responded,
  DefinitionKey extends keyof typeof apiDefinitions,
  CurrentConfig extends Alova2MethodConfig<any>
> =
  CollapsedAlova extends Alova<
      AlovaGenerics<
        any,
        any,
        infer RequestConfig,
        infer Response,
        infer ResponseHeader,
        infer L1Cache,
        infer L2Cache,
        infer SE
      >
    >
    ? Method<
      AlovaGenerics<
        CurrentConfig extends undefined
          ? ExtractUserDefinedTransformed<DefinitionKey, Responded>
          : CurrentConfig['transform'] extends (...args: any[]) => any
            ? Awaited<ReturnType<CurrentConfig['transform']>>
            : ExtractUserDefinedTransformed<DefinitionKey, Responded>,
        any,
        RequestConfig,
        Response,
        ResponseHeader,
        L1Cache,
        L2Cache,
        SE
      >
    >
    : never;

export interface Category {
  id?: number;
  name?: string;
}

export interface Tag {
  id?: number;
  name?: string;
}

export interface Pet {
  id?: number;
  name: string;
  category?: Category;
  photoUrls: string[];
  tags?: Tag[];
  /**
   * pet status in the store
   */
  status?: 'available' | 'pending' | 'sold';
}

export interface Order {
  id?: number;
  petId?: number;
  quantity?: number;
  shipDate?: string;
  /**
   * Order Status
   */
  status?: 'placed' | 'approved' | 'delivered';
  complete?: boolean;
}

export interface User {
  id?: number;
  username?: string;
  firstName?: string;
  lastName?: string;
  email?: string;
  password?: string;
  phone?: string;
  /**
   * User Status
   */
  userStatus?: number;
}

export interface PaginatedResponse<T> {
  current_page: number;
  data: T[];
  first_page_url: string;
  from: number | null;
  last_page: number;
  last_page_url: string;
  links: {
    url: string | null;
    label: string;
    active: boolean;
  }[];
  next_page_url: string | null;
  path: string;
  per_page: number;
  prev_page_url: string | null;
  to: number | null;
  total: number;
}

export interface FeedPost {
  created_at: any;
  id: string;
  author: {
    nickname: any; name: string; avatar?: string
  };
  content: string;
  topics?: string[];
  mealReference?: { mealType: string; totalCalories: number };
  likes: number;
  comments: number;
  timestamp: string;
  isLiked: boolean;
}

export interface DiarySummary {
  dailyGoal: {
    calories: number;
    protein: number;
    fat: number;
    carbs: number;
  };
  totalIntake: {
    calories: number;
    protein: number;
    fat: number;
    carbs: number;
  };
  burnedCalories: number;
}

export interface HistoryMeal {
  id: string | number;
  mealType: string;
  totalCalories: number;
  items: { name: string; amount: string }[];
}

export interface HistoryItem {
  id: string | number;
  date: string;
  totalCalories: number;
  totalBurned: number;
  mealCount: number;
  meals: HistoryMeal[];
}

export interface FoodItem {
  id: string;
  name: string;
  amount: number;
  unit: string;
  calories: number;
  protein: number;
  fat: number;
  carbs: number;
}

export interface FoodUnitNutrition {
  calories: string | number;
  protein: string | number;
  carbs: string | number;
  fibers: string | number;
}

export interface FoodUnit {
  unit_id: number;
  unit_name: string;
  weight: number;
  is_default: boolean;
  nutrition: FoodUnitNutrition;
}

export interface TmpFoodUnit {
  id: number,
  name: string,
  isDefault: boolean,
  nutrition: FoodUnitNutrition
}

export interface FoodInfo {
  id: number;
  name: string;
  category: string;
  unit: string;
  calories: number;
  protein: number;
  carbs: number;
  fat?: number;
  fiber?: number;
  units?: FoodUnit[];
}

export interface Topic {
  id: number;
  title: string;
  thumb?: string | null;
  description?: string;
  join?: number;
  post?: number;
}

export interface UserStats {
  name: string;
  joinDays: number;
  totalRecords: number;
  avgCalories: number;
  currentWeight: number;
  targetWeight: number;
  height: number;
  age: number;
  gender: string;
  dailyGoal?: {
    calories: number;
    protein: number;
    fat: number;
    carbs: number;
  };
}

export interface ApiResponse {
  code?: number;
  type?: string;
  message?: string;
}

declare global {
  interface Apis {
    user: {
      stats<Config extends Alova2MethodConfig<UserStats>>(
        config?: Config
      ): Alova2Method<UserStats, 'user.stats', Config>;
      information<Config extends Alova2MethodConfig<any>>(
        config?: Config
      ): Alova2Method<any, 'user.information', Config>;
    };
    food: {
      list<Config extends Alova2MethodConfig<{
        list: FoodInfo[];
        total: number;
        page: number;
        pageSize: number;
        hasMore: boolean;
        categories: string[];
      }> & {
        params?: { keyword?: string; category?: string; page?: number; pageSize?: number };
      }>(
        config?: Config
      ): Alova2Method<{
        list: FoodInfo[];
        total: number;
        page: number;
        pageSize: number;
        hasMore: boolean;
        categories: string[];
      }, 'food.list', Config>;
      recognize<Config extends Alova2MethodConfig<(FoodInfo & { confidence: number })[]>>(
        config?: Config
      ): Alova2Method<(FoodInfo & { confidence: number })[], 'food.recognize', Config>;
      detail<Config extends Alova2MethodConfig<FoodInfo> & {
        params: { id: string };
      }>(
        config: Config
      ): Alova2Method<FoodInfo, 'food.detail', Config>;
      categories<Config extends Alova2MethodConfig<{ name: string; count: number }[]>>(
        config?: Config
      ): Alova2Method<{ name: string; count: number }[], 'food.categories', Config>;
      search<Config extends Alova2MethodConfig<PaginatedResponse<FoodInfo>> & {
        params?: { name?: string; page?: number; pageSize?: number };
      }>(
        config?: Config
      ): Alova2Method<PaginatedResponse<FoodInfo>, 'food.search', Config>;
    };
    auth: {
      login<Config extends Alova2MethodConfig<any> & {
        data: { code: string }
      }>(config: Config): Alova2Method<any, 'auth.login', Config>;
      sms: {
        login<Config extends Alova2MethodConfig<any> & {
          data: { mobile: string; code: string }
        }>(config: Config): Alova2Method<any, 'auth.sms.login', Config>;
      };
    };
    diary: {
      summary<Config extends Alova2MethodConfig<DiarySummary>>(
        config?: Config
      ): Alova2Method<DiarySummary, 'diary.summary', Config>;
      meals<Config extends Alova2MethodConfig<Record<string, FoodItem[]>>>(
        config?: Config
      ): Alova2Method<Record<string, FoodItem[]>, 'diary.meals', Config>;
      history<Config extends Alova2MethodConfig<PaginatedResponse<HistoryItem>> & {
        params?: { page?: number; pageSize?: number };
      }>(
        config?: Config
      ): Alova2Method<PaginatedResponse<HistoryItem>, 'diary.history', Config>;
      addFood<
        Config extends Alova2MethodConfig<FoodItem> & {
          data: { type: string; food: Omit<FoodItem, 'id'> };
        }
      >(
        config: Config
      ): Alova2Method<FoodItem, 'diary.addFood', Config>;
      deleteFood<
        Config extends Alova2MethodConfig<{ message: string }> & {
          params: { id: string };
        }
      >(
        config: Config
      ): Alova2Method<{ message: string }, 'diary.deleteFood', Config>;
    };
    feed: {
      list<Config extends Alova2MethodConfig<PaginatedResponse<FeedPost>> & {
        params?: { page?: number; pageSize?: number };
      }>(
        config?: Config
      ): Alova2Method<PaginatedResponse<FeedPost>, 'feed.list', Config>;
      create<Config extends Alova2MethodConfig<any> & {
        data: any
      }>(config: Config): Alova2Method<any, 'feed.create', Config>;
      like<
        Config extends Alova2MethodConfig<{ isLiked: boolean; likes: number }> & {
          data: { id: string };
        }
      >(
        config: Config
      ): Alova2Method<{ isLiked: boolean; likes: number }, 'feed.like', Config>;
    };
    topic: {
      search<Config extends Alova2MethodConfig<any> & {
        params?: any
      }>(config?: Config): Alova2Method<any, 'topic.search', Config>;
      hot<Config extends Alova2MethodConfig<Topic[]>>(config?: Config): Alova2Method<Topic[], 'topic.hot', Config>;
      create<Config extends Alova2MethodConfig<Topic> & {
        data: { title: string }
      }>(config: Config): Alova2Method<Topic, 'topic.create', Config>;
    };
  }

  var Apis: Apis;
}
