/* tslint:disable */
/* eslint-disable */
/**
 * Swagger Petstore - OpenAPI 3.0 - version 1.0.27
 *
 * This is a sample Pet Store Server based on the OpenAPI 3.0 specification.  You can find out more about
 Swagger at [https://swagger.io](https://swagger.io). In the third iteration of the pet store, we&#x27;ve switched to the design first approach!
 You can now help us improve the API whether it&#x27;s by making changes to the definition itself or to the code.
 That way, with time, we can improve the API in general, and expose some of the new features in OAS3.

 Some useful links:
 - [The Pet Store repository](https://github.com/swagger-api/swagger-petstore)
 - [The source API definition for the Pet Store](https://github.com/swagger-api/swagger-petstore/blob/master/src/main/resources/openapi.yaml)
 *
 * OpenAPI version: 3.0.4
 *
 * Contact:
 *
 * NOTE: This file is auto generated by the alova's vscode plugin.
 *
 * https://alova.js.org/devtools/vscode
 *
 * **Do not edit the file manually.**
 */
import type { Alova, AlovaMethodCreateConfig, AlovaGenerics, Method } from 'alova';
import type { $$userConfigMap, alovaInstance } from '.';
import type apiDefinitions from './apiDefinitions';

type CollapsedAlova = typeof alovaInstance;
type UserMethodConfigMap = typeof $$userConfigMap;

type Alova2MethodConfig<Responded> =
  CollapsedAlova extends Alova<
      AlovaGenerics<
        any,
        any,
        infer RequestConfig,
        infer Response,
        infer ResponseHeader,
        infer L1Cache,
        infer L2Cache,
        infer SE
      >
    >
    ? Omit<
      AlovaMethodCreateConfig<
        AlovaGenerics<Responded, any, RequestConfig, Response, ResponseHeader, L1Cache, L2Cache, SE>,
        any,
        Responded
      >,
      'params'
    >
    : never;

// Extract the return type of transform function that define in $$userConfigMap, if it not exists, use the default type.
type ExtractUserDefinedTransformed<
  DefinitionKey extends keyof typeof apiDefinitions,
  Default
> = DefinitionKey extends keyof UserMethodConfigMap
  ? UserMethodConfigMap[DefinitionKey]['transform'] extends (...args: any[]) => any
    ? Awaited<ReturnType<UserMethodConfigMap[DefinitionKey]['transform']>>
    : Default
  : Default;
type Alova2Method<
  Responded,
  DefinitionKey extends keyof typeof apiDefinitions,
  CurrentConfig extends Alova2MethodConfig<any>
> =
  CollapsedAlova extends Alova<
      AlovaGenerics<
        any,
        any,
        infer RequestConfig,
        infer Response,
        infer ResponseHeader,
        infer L1Cache,
        infer L2Cache,
        infer SE
      >
    >
    ? Method<
      AlovaGenerics<
        CurrentConfig extends undefined
          ? ExtractUserDefinedTransformed<DefinitionKey, Responded>
          : CurrentConfig['transform'] extends (...args: any[]) => any
            ? Awaited<ReturnType<CurrentConfig['transform']>>
            : ExtractUserDefinedTransformed<DefinitionKey, Responded>,
        any,
        RequestConfig,
        Response,
        ResponseHeader,
        L1Cache,
        L2Cache,
        SE
      >
    >
    : never;

export interface Category {
  id?: number;
  name?: string;
}

export interface Tag {
  id?: number;
  name?: string;
}

export interface Pet {
  id?: number;
  name: string;
  category?: Category;
  photoUrls: string[];
  tags?: Tag[];
  /**
   * pet status in the store
   */
  status?: 'available' | 'pending' | 'sold';
}

export interface Order {
  id?: number;
  petId?: number;
  quantity?: number;
  shipDate?: string;
  /**
   * Order Status
   */
  status?: 'placed' | 'approved' | 'delivered';
  complete?: boolean;
}

export interface User {
  id?: number;
  username?: string;
  firstName?: string;
  lastName?: string;
  email?: string;
  password?: string;
  phone?: string;
  /**
   * User Status
   */
  userStatus?: number;
}

export interface ApiResponse {
  code?: number;
  type?: string;
  message?: string;
}

declare global {
  interface Apis {
    [x: string]: any;

    feed: {
      /**
       * Get feed list
       */
      list<Config extends Alova2MethodConfig<any> & { params?: any }>(
        config?: Config
      ): Alova2Method<any, 'feed.list', Config>;
      /**
       * Create new post
       */
      create<Config extends Alova2MethodConfig<any> & { data?: any }>(
        config?: Config
      ): Alova2Method<any, 'feed.create', Config>;
      /**
       * Like/Unlike post
       */
      like<Config extends Alova2MethodConfig<any> & { data?: any }>(
        config?: Config
      ): Alova2Method<any, 'feed.like', Config>;
      /**
       * Get post detail
       */
      detail<Config extends Alova2MethodConfig<any> & { params: { id: number | string } }>(
        config: Config
      ): Alova2Method<any, 'feed.detail', Config>;
    };
    store: {
      /**
       * ---
       *
       * [GET] Returns pet inventories by status.
       *
       * **path:** /store/inventory
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = Record<string, number>
       * ```
       */
      getInventory<Config extends Alova2MethodConfig<Record<string, number>>>(
        config?: Config
      ): Alova2Method<Record<string, number>, 'store.getInventory', Config>;
      /**
       * ---
       *
       * [POST] Place an order for a pet.
       *
       * **path:** /store/order
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   id?: number
       *   petId?: number
       *   quantity?: number
       *   shipDate?: string
       *   // Order Status
       *   status?: 'placed' | 'approved' | 'delivered'
       *   complete?: boolean
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   id?: number
       *   petId?: number
       *   quantity?: number
       *   shipDate?: string
       *   // Order Status
       *   status?: 'placed' | 'approved' | 'delivered'
       *   complete?: boolean
       * }
       * ```
       */
      placeOrder<
        Config extends Alova2MethodConfig<Order> & {
          data: Order;
        }
      >(
        config: Config
      ): Alova2Method<Order, 'store.placeOrder', Config>;
      /**
       * ---
       *
       * [GET] Find purchase order by ID.
       *
       * **path:** /store/order/{orderId}
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   // ID of order that needs to be fetched
       *   orderId: number
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   id?: number
       *   petId?: number
       *   quantity?: number
       *   shipDate?: string
       *   // Order Status
       *   status?: 'placed' | 'approved' | 'delivered'
       *   complete?: boolean
       * }
       * ```
       */
      getOrderById<
        Config extends Alova2MethodConfig<Order> & {
          pathParams: {
            /**
             * ID of order that needs to be fetched
             */
            orderId: number;
          };
        }
      >(
        config: Config
      ): Alova2Method<Order, 'store.getOrderById', Config>;
      /**
       * ---
       *
       * [DELETE] Delete purchase order by identifier.
       *
       * **path:** /store/order/{orderId}
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   // ID of the order that needs to be deleted
       *   orderId: number
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = null
       * ```
       */
      deleteOrder<
        Config extends Alova2MethodConfig<null> & {
          pathParams: {
            /**
             * ID of the order that needs to be deleted
             */
            orderId: number;
          };
        }
      >(
        config: Config
      ): Alova2Method<null, 'store.deleteOrder', Config>;
    };
    user: {
      [x: string]: any;
    };
    food: {
      [x: string]: any;
      /**
       * Get food recommendation
       */
      recommendation<Config extends Alova2MethodConfig<any>>(
        config?: Config
      ): Alova2Method<any, 'food.recommendation', Config>;
      /**
       * Get food recognition result by task id
       */
    };
    task: {
      enquire<Config extends Alova2MethodConfig<any> & { params: { taskId: string | number } }>(
        config: Config
      ): Alova2Method<{ status: 'pending' | 'completed' | 'failed'; data?: any }, 'task.enquire', Config>;
    }
    nutrition: {
      stats<Config extends Alova2MethodConfig<any>>(
        config?: Config
      ): Alova2Method<any, 'nutrition.stats', Config>;
    },
    article: {
      notices<Config extends Alova2MethodConfig<any>>(
        config?: Config
      ): Alova2Method<any, 'article.notices', Config>;
      userAgreement<Config extends Alova2MethodConfig<any>>(
        config?: Config
      ): Alova2Method<any, 'article.userAgreement', Config>;
      info<Config extends Alova2MethodConfig<any>>(
        config?: { params: { id: any, type: any } }
      ): Alova2Method<any, "article.info", Config>;
    },
    diary: {
      [x: string]: any;
      summary<Config extends Alova2MethodConfig<any>>(
        config?: Config
      ): Alova2Method<any, 'diary.summary', Config>;
    },
    option: {
      [x: string]: any;
    }
  }

  var Apis: Apis;
}
